import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const PoppinsFont = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={`flex flex-col ${PoppinsFont.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
